spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=MSS301_OrderServiceDB
    username: sa
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8080

orchid:
  server:
    url: http://localhost:8082

account:
  server:
    url: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1